### ISSUE TITLE
docker-compose with developer image fails

### ISSUE THREAD

**Issue by spekary** [zephyrproject-rtos/docker-image#89]
Using this docker-compose.yml file:

```
version: "2"
services:
    zephyr:
        image: docker.io/zephyrprojectrtos/zephyr-build:latest
        container_name: zephyr
        volumes:
            - /myworkspace:/workdir
        ports:
            - "5900:5900"
```

I get the following error starting the container:

zephyr    | Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
zephyr    | 
zephyr    | ERROR: openbox-xdg-autostart requires PyXDG to be installed
